version: "3.8"
services:
    mysql:
        image: mysql:8
        container_name: MySql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: offres_emploi
            MYSQL_USER: bcr
            MYSQL_PASSWORD: bcr
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - api-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8081:80"
    api:
        build: ./emplois
        container_name: api_php
        ports:
            - "8080:80"
        volumes:
            - ./emplois:/var/www/html/
        networks:
            - api-network
volumes:
    dbdata:

networks:
    api-network:
        driver: bridge
